export const IPC_CHANNELS = {
  tracker: {
    start: 'tracker:start',
    stop: 'tracker:stop',
    pause: 'tracker:pause',
    resume: 'tracker:resume',
    getCurrentActivity: 'tracker:getCurrentActivity',
    setAfkThreshold: 'tracker:setAfkThreshold',
    activityUpdate: 'tracker:activityUpdate',
    idleChange: 'tracker:idleChange',
  },
  db: {
    getSessions: 'db:getSessions',
    getSessionById: 'db:getSessionById',
    getActivitiesBySessionId: 'db:getActivitiesBySessionId',
    saveSession: 'db:saveSession',
    saveActivities: 'db:saveActivities',
    getStreak: 'db:getStreak',
    getUserStats: 'db:getUserStats',
    getSessionAnalysis: 'db:getSessionAnalysis',
    getLocalStat: 'db:getLocalStat',
    setLocalStat: 'db:setLocalStat',
    getUnlockedAchievements: 'db:getUnlockedAchievements',
    unlockAchievement: 'db:unlockAchievement',
    getAppUsageStats: 'db:getAppUsageStats',
    getTopAppsByCategory: 'db:getTopAppsByCategory',
    getTopTitlesByCategory: 'db:getTopTitlesByCategory',
    getCategoryStats: 'db:getCategoryStats',
    getContextSwitchCount: 'db:getContextSwitchCount',
    getSessionCount: 'db:getSessionCount',
    getTotalSeconds: 'db:getTotalSeconds',
    getWindowTitleStats: 'db:getWindowTitleStats',
    getHourlyDistribution: 'db:getHourlyDistribution',
    getTotalKeystrokes: 'db:getTotalKeystrokes',
    getKeystrokesByApp: 'db:getKeystrokesByApp',
    getSkillXP: 'db:getSkillXP',
    addSkillXP: 'db:addSkillXP',
    getAllSkillXP: 'db:getAllSkillXP',
    getActiveGoals: 'db:getActiveGoals',
    getAllGoals: 'db:getAllGoals',
    createGoal: 'db:createGoal',
    completeGoal: 'db:completeGoal',
    updateGoal: 'db:updateGoal',
    deleteGoal: 'db:deleteGoal',
    getGoalProgress: 'db:getGoalProgress',
    getTasks: 'db:getTasks',
    createTask: 'db:createTask',
    toggleTask: 'db:toggleTask',
    updateTaskText: 'db:updateTaskText',
    deleteTask: 'db:deleteTask',
    clearDoneTasks: 'db:clearDoneTasks',
    getDailyTotals: 'db:getDailyTotals',
    addSkillXPLog: 'db:addSkillXPLog',
    getSkillXPHistory: 'db:getSkillXPHistory',
    saveCheckpoint: 'db:saveCheckpoint',
    getCheckpoint: 'db:getCheckpoint',
    clearCheckpoint: 'db:clearCheckpoint',
  },
  ai: {
    analyzeSession: 'ai:analyzeSession',
    analyzeOverview: 'ai:analyzeOverview',
  },
  settings: {
    getAutoLaunch: 'settings:getAutoLaunch',
    setAutoLaunch: 'settings:setAutoLaunch',
  },
  notify: {
    show: 'notify:show',
  },
  data: {
    exportSessions: 'data:exportSessions',
    getLogsPath: 'data:getLogsPath',
    openLogsFolder: 'data:openLogsFolder',
  },
  window: {
    flashFrame: 'window:flashFrame',
  },
  updater: {
    status: 'updater:status',
    install: 'updater:install',
  },
} as const
